# Site settings
title: Claudiu Creanga Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Claudiu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://claudiucreanga.me" # the base hostname & protocol for your site
twitter_username: ClaudiuCreanga
github_username:  ClaudiuCreanga

# Build settings
markdown: kramdown
